# =============================================================================
# SNK场景生成配置文件
# Space Networking Kit - Scenario Generation Configuration
# =============================================================================

# 轨道高度与平均运动速度对照表（每天绕地圈数）
# 用于快速查找不同高度对应的mean_motion_rev_per_day参数
# 500km 15.230674475111606;  # 低轨道，高速度，小覆盖范围
# 550km 15.065933778247187   # Starlink典型高度
# 700km 14.589111948816067   # 中等高度
# 1550km  12.247043443986453 # 高轨道，低速度，大覆盖范围
# 1575km 12.305066862264445  # 接近中地球轨道
# 1000km 13.707617251982475; # 平衡高度
# 2000km 11.326343337319642  # 高轨道

# =============================================================================
# 基础路径配置
# =============================================================================

# 项目根目录路径（已弃用，保留兼容性）
root: "./"

# 输出数据存储路径
# 所有生成的CZML文件、TLE文件、元数据将保存在此目录
# 使用相对路径，相对于snk_scenario目录
dump_path: "../snk_visualizer/data/output"

# =============================================================================
# 时间配置
# =============================================================================

# 仿真开始时间（ISO 8601格式）
# 建议使用2000年作为基准年，便于TLE格式兼容
start_time: "2000-01-01T00:00:00"

# 仿真结束时间（ISO 8601格式）
# 仿真持续时间 = end_time - start_time
end_time: "2000-01-02T00:00:00"

# 轨迹采样时间步长（秒）
# 值越小轨迹越平滑但数据量越大，建议范围：60-300秒
time_step: 100

# 随机数种子
# 用于确保ISL链路可靠性模拟的可重现性
random_seed: 123

# =============================================================================
# 性能配置
# =============================================================================

# 是否启用多线程处理（实验性功能）
# 当前版本建议保持false
multi_threading: false

# 多线程处理时的批处理大小
# 仅在multi_threading=true时有效
mpt_item_len: 30


# =============================================================================
# 星座配置
# =============================================================================

constellations:

  # 星座层名称（可定义多个层实现多层星座）
  LAYER0:
    # 是否启用此星座层
    enable: true
    
    # 轨道层编号（用于卫星ID生成，从0开始）
    shellNo: 0
    
    # 轨道数量（轨道面数量）
    num_orbits: 10
    
    # 每个轨道的卫星数量
    num_sats_per_orbit: 10
    
    # 相位因子（Walker星座参数F）
    # 控制相邻轨道间卫星的相对位置偏移
    phase_factor: 0
    
    # 是否使用自定义RAAN增量（升交点赤经增量）
    # false: 使用360/num_orbits自动计算
    raan_increment: false


    # =================================================================
    # 轨道生成方式（三选一，只能启用一种）
    # =================================================================
    
    # 方式1：从种子TLE文件生成（使用现有TLE作为模板）
    seed_tle:  #generate from seed tle
    #      seed_tle: "./Molniya_seed.txt"  # TLE文件路径

    # 方式2：使用SGP4参数直接生成（高级用户）
    sgp: #generate from sgp format
    #      phase_diff: true  # 是否启用轨道间相位差
    #      mean_motion_rev_per_day: 13.707617251982475  # 平均运动速度
    #      inclination_degree: 53  # 轨道倾角（度）
    #      perigee_degree: 268.4266  # 近地点幅角（度）
    #      eccentricity: 0.0000001  # 离心率

    # 方式3：从种子卫星参数生成（推荐方式）
    seed_satellite: #generate from seed satellite
      # 平均运动速度（每天绕地圈数）
      # 15.065对应约550km高度（Starlink典型高度）
      mean_motion_rev_per_day: 15.065933778247187
      
      # 轨道倾角（度）
      # 53度是Starlink的典型倾角，提供全球覆盖
      inclination_degree: 53
      
      # 近地点幅角（度）
      # 0度表示近地点在升交点
      perigee_degree: 0
      
      # 平近点角（度）
      # 卫星在轨道上的初始位置
      mean_anomaly_degree: 0
      
      # 升交点赤经（度）
      # 360度表示从0度开始，后续轨道自动递增
      raan: 360
      
      # 离心率
      # 0.0000001表示近圆轨道
      eccentricity: 0.0000001

    # =================================================================
    # 卫星3D模型配置
    # =================================================================
    
    sat_model:
      # 卫星3D模型文件路径（GLTF格式）
      # 用于在Cesium中显示卫星的3D外观
      gltf: "/Libs/3d_models/commSat.glb"

    # =================================================================
    # 传感器配置（通信覆盖范围可视化）
    # =================================================================
    
    sensor:
      # 传感器转向角（度）
      # 46度对应Starlink的典型仰角限制
      steering_angle: 46
      
      # 传感器高度（米）
      # 1000000米 = 1000km，表示传感器覆盖范围
      height: 1000000
      
      # 传感器颜色和透明度（RGBA）
      # [红, 绿, 蓝, 透明度]
      rgba: [0,10,10,0.02]
      
      # 高度因子（传感器锥体高度倍数）
      # 0.25表示传感器高度为height的25%
      height_factor: 0.25


    # =================================================================
    # 星间链路（ISL）配置
    # =================================================================
    
    ISL:
      # 是否启用星间链路
      enable: true
      
      # 是否使用循环拓扑（首尾轨道相连）
      # true: 轨道0与最后一个轨道相连
      # false: 轨道不形成循环
      circuit: true
      
      # 链路可靠性模拟的时间步长倍数
      # 用于生成方波信号模拟链路间歇性
      time_steps: 10

      # 轨道内链路（iISL - intra-orbit ISL）
      iISL:
        # 连接特征（卫星间相对位置偏移）
        # [1] 表示连接下一颗卫星（+1位置）
        full_conn_features: [1]
        
        # 连接特征周期模式
        # [[-1]] 表示所有卫星都使用相同的连接模式
        conn_features_periods: [[-1]]
        
        # 链路颜色（RGBA）
        # 蓝色表示轨道内链路
        rgba: [0,0,255,255]
        
        # 占空比（链路可用时间比例）
        # 1.0 = 100%可用，0.5 = 50%可用
        duty_ratio: 1
        
        # 周期数量（用于生成方波信号）
        # 24个周期覆盖整个仿真时间
        num_periods: 24

      # 轨道间链路（sISL - inter-orbit ISL）
      sISL:
        # 连接特征（支持多跳连接）
        # [-2,-1,0] 表示连接前2颗、前1颗、同位置卫星
        full_conn_features: [-2,-1,0]
        
        # 连接特征周期模式
        # [[0]] 表示所有轨道都使用相同的连接模式
        conn_features_periods: [[0]]
        
        # 链路颜色（RGBA）
        # 绿色表示轨道间链路
        rgba: [0,255,0,255]
        
        # 占空比（链路可用时间比例）
        duty_ratio: 1
        
        # 周期数量
        num_periods: 24









